name: Build and Deploy to NKS

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image version tag
      id: version
      run: |
        TAG="v$(printf '%02d' ${{ github.run_number }})"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Log in to NCP Container Registry
      uses: docker/login-action@v2
      with:
        registry: zcon-nipa-container-registry.kr.ncr.ntruss.com
        username: ${{ secrets.NCP_ACCESSKEY }}
        password: ${{ secrets.NCP_SECRETKEY }}

    - name: Build Docker image
      run: |
        docker build -t zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }} .

    - name: Push Docker image
      run: |
        docker push zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Install ncp-iam-authenticator
      run: |
        curl -Lo ncp-iam-authenticator https://github.com/ncloudtech/ncp-iam-authenticator/releases/latest/download/ncp-iam-authenticator_linux_amd64
        chmod +x ncp-iam-authenticator
        sudo mv ncp-iam-authenticator /usr/local/bin/
        pwd
        ls -l $HOME

    - name: Generate kubeconfig with ncp-iam-authenticator
      env:
        NCP_ACCESSKEY: ${{ secrets.NCP_ACCESSKEY }}
        NCP_SECRETKEY: ${{ secrets.NCP_SECRETKEY }}
      run: |
        ./ncp-iam-authenticator create-kubeconfig \
          --region KR \
          --clusterUuid 25c062ae-b203-4e84-94bf-282fdf27f9b6 \
          --output $HOME/.kube/config

    - name: Check NKS nodes
      run: |
        kubectl get nodes

    - name: Deploy to NKS
      run: |
        kubectl set image deployment/api-consumer api-consumer=zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }} --record -n daun
        kubectl rollout status deployment/api-consumer -n daun
