name: Build and Deploy to NKS

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image version tag
      id: version
      run: |
        TAG="v$(printf '%02d' ${{ github.run_number }})"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Log in to NCP Container Registry
      uses: docker/login-action@v2
      with:
        registry: zcon-nipa-container-registry.kr.ncr.ntruss.com
        username: ${{ secrets.NCP_ACCESSKEY }}
        password: ${{ secrets.NCP_SECRETKEY }}

    - name: Build Docker image
      run: |
        docker build -t zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }} .

    - name: Push Docker image
      run: |
        docker push zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to NKS
      run: |
        kubectl set image deployment/api-consumer api-consumer=zcon-nipa-container-registry.kr.ncr.ntruss.com/data_insert:${{ steps.version.outputs.tag }} --record -n daun
        kubectl rollout status deployment/api-consumer -n daun
